### ISSUE TITLE
Quizzes: add to eliademy

### ISSUE THREAD

**Issue by tosteiner** [OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers#11]
@Protohedgehog Jon, do you think adding the [quiz set](https://github.com/OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers/blob/master/content_development/04-quizzes.md) to eliademy would make sense, or too early? I do have a bit of free time on my hands at the moment, and would be happy to do this :) 

Also, and apart from that, do you need a wingman 👾 for any of the open tasks re: content development? Or should I just have a go at any one of them... ?

**Comment by Protohedgehog** [comment]
@tosteiner I think migrating it over might not be a bad idea. We can always edit it later on in Eliademy.

If you wanted to have a bash at the OA literature search task with @johav that might be nice too. Or go through all of the currently drafted content and add notes on things that you would explicitly expect to see there, to make sure I don't miss things out!

**Comment by tosteiner** [comment]
Fab! am off to meet friends now, but will continue with this later 🌞

**Comment by tosteiner** [comment]
note to self: pick up on https://github.com/OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers/issues/11#issuecomment-515670986

### Current state of issue:

- [x] Quiz transfer to eliademy: see [here](https://eliademy.com/app/a/quizzes/920824)
- [x] Re-check quiz for inconsistencies and missing links (questions 6 and 8) - fix prior to release!

**Comment by tosteiner** [comment]
all set with #23 - close
