### ISSUE TITLE
Follow a naming convention

### ISSUE THREAD

**Issue by SamGuay** [OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers#16]
It would be great if we all follow the same naming convention so the repo keeps the same structure as will have the module on Eliademy. 

Also, this would help the consistency between file names and less swearing when moving files (that have 'spaces' in their name) in a terminal.
 * Example of this repo: Some files are named `Main_xxx_xxx`, others `MAIN_Xxx Xxx`, ect.

I suggest a naming convention where we can order all files according numerical order, as simple as
 * 1_MAIN_global.md
 * 2_MAIN_introduction.md
 * 1_MAIN_xxx_xxx_xxx_.md

**Comment by Protohedgehog** [comment]
This is an excellent idea @SamGuay. Lemme get on it today.

**Comment by Protohedgehog** [comment]
OK, done! Hopefully this is easier now :)
