### ISSUE TITLE
Add research grant proposals to the research pipeline

### ISSUE THREAD

**Issue by johnsamuelwrites** [OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers#3]
A research grant proposal is the starting point of the research pipeline. It may be accepted, rejected or in a waiting list for further detailed review. Journals like [RIOJournal](https://riojournal.com/) give an opportunity to upload the grant proposals. Nevertheless, very less has been discussed on the pros and cons of uploading them. 

Major questions that need to be discussed:
* Should all accepted proposals be published online and granted a persistent identifier?
* In case of rejected grant proposals, how wise is it to upload them? Will it create a bias for future grant requests?
* Should proposal grant reviews be made publicly available?
* What are the possible open licences for grant proposals and the review comments?
* Any possible issues on uploading accepted grant proposals? Who should upload them? Funding agencies? or individual contributors?
* Should contributors to the proposal upload a grant proposal like preprint papers at the time of submission? Is it possible that funding agency directly refer the 'preprint' like grant request?

**Comment by Daniel-Mietchen** [comment]
@johnsamuelwrites I think these questions would be great fodder for http://ask-open-science.org/ . Can you post them (or variants thereof) there?

**Comment by johnsamuelwrites** [comment]
Some [pointers](https://twitter.com/EvoMRI/status/1055164152921112576) from @Daniel-Mietchen : 
* Mietchen, Daniel, Ross Mounce, and Lyubomir Penev. “Publishing the Research Process.” Research Ideas and Outcomes 1 (December 17, 2015): e7547. https://doi.org/10.3897/rio.1.e7547.
* Mietchen, Daniel. “The Transformative Nature of Transparency in Research Funding.” PLOS Biology, vol. 12, no. 12, Dec. 2014, p. e1002027. PLoS Journals, doi:10.1371/journal.pbio.1002027.
* Gurwitz, David, Elena Milanesi, and Thomas Koenig. “Grant Application Review: The Case of Transparency.” PLOS Biology 12, no. 12 (December 2, 2014): e1002010. https://doi.org/10.1371/journal.pbio.1002010.

**Comment by johnsamuelwrites** [comment]
@Daniel-Mietchen, if approved, it will be available here: https://ask-open-science.org/1348/how-include-research-grant-proposals-the-research-pipeline

**Comment by Daniel-Mietchen** [comment]
You pasted the first one twice - should be Mietchen D (2014) The Transformative Nature of Transparency in Research Funding. PLoS Biol 12(12): e1002027. https://doi.org/10.1371/journal.pbio.1002027 instead.

**Comment by johnsamuelwrites** [comment]
@Daniel-Mietchen Updated.

**Comment by Protohedgehog** [comment]
@johnsamuelwrites do you think this still has place within the existing structure now..?

**Comment by johnsamuelwrites** [comment]
@Protohedgehog I feel that research grant proposals (at least starting with the accepted and funded ones) have a place in the research pipeline and their open access helps other research members. 
I am not sure whether a separate module is needed for this topic. That's why I added this issue in the module 6, which covers open access. But if you are interested in opening a new module on discussion of different topics, I leave the decision to you.

**Comment by Protohedgehog** [comment]
Sorry @johnsamuelwrites I meant within the structure here: https://github.com/OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers/tree/master/content_development - we have 15 sub-topics now for this module. Would this fit in, or shall we add a new one?

**Comment by Protohedgehog** [comment]
@johnsamuelwrites any thoughts on this? I have some time to integrate them if you think it fits

**Comment by johnsamuelwrites** [comment]
[Chapter 14](https://github.com/OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers/blob/master/content_development/14_MAIN_Pre-registration.md) (Pre-registration) may cover this topic. Pre-registration of research plans (which is indeed the first step before research is carried out) is discussed [here](https://cos.io/prereg/), [here](https://www.psychologicalscience.org/publications/psychological_science/preregistration) and [here](https://www.sciencemag.org/news/2018/09/more-and-more-scientists-are-preregistering-their-studies-should-you).
