### ISSUE TITLE
Incorporate OLH docu video into module

### ISSUE THREAD

**Issue by tosteiner** [OpenScienceMOOC/Module-6-Open-Access-to-Research-Papers#6]
The Open Library of the Humanities has just (recently released)[https://www.openlibhums.org/news/319/] a great video brief on the matter of OA for scholarly publication. 

Here's the video link: https://www.youtube.com/watch?v=Yp0Jko0ZBcE

I think this would be an excellent piece to add to this module, and since it's openly licensed for re-use ( 🥇 ), there's no barriers for us to do so - just wonderful ❤️

**Comment by Protohedgehog** [comment]
Such a great idea, thanks @tosteiner!

**Comment by Protohedgehog** [comment]
Note, add this video on CC licensing too https://www.youtube.com/watch?v=4ZvJGV6YF6Y

**Comment by Protohedgehog** [comment]
Have added both of these in on Eliademy now!
